---
- name: Configuration et Securisation du Serveur Web Production
  hosts: serveurs_web
  become: false
  tasks:

    - name: Mettre a jour les paquets systeme (apt update)
      apt:
        update_cache: yes

    - name: Installer le serveur Web Nginx
      apt:
        name: nginx
        state: present

    - name: Deployer la page web de l Universite Espoir d Afrique
      copy:
        content: "<h1>Serveur Securise par le Master GGT via Ansible !</h1>"
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Demarrer et activer Nginx au boot
      service:
        name: nginx
        state: started
        enabled: yes
